USE ister_v2;
CREATE TABLE IF NOT EXISTS ister_bullet (
    BulletID INT AUTO_INCREMENT PRIMARY KEY,
    NodeID INT NOT NULL,
    SiraNo INT DEFAULT 0,
    Icerik LONGTEXT NOT NULL,
    OlusturanID INT,
    OlusturmaTarihi DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (NodeID) REFERENCES ister_node(NodeID) ON DELETE CASCADE
);
